from typing import Any

class Get:
    activities: Any
    activity_descriptions: Any
    activity_rates: Any
    allocations: Any
    bank_accounts: Any
    bank_transactions: Any
    bank_transfers: Any
    bill_themes: Any
    billable_clients: Any
    billable_matters: Any
    bills: Any
    calendar_entries: Any
    calendar_entry_event_types: Any
    calendars: Any
    clio_payments: Any
    comments: Any
    communications: Any
    contacts: Any
    conversation_messages: Any
    conversations: Any
    court_rules: Any
    credit_memos: Any
    currencies: Any
    custom_actions: Any
    custom_field_sets: Any
    custom_fields: Any
    damages: Any
    document_archives: Any
    document_automations: Any
    document_categories: Any
    document_templates: Any
    documents: Any
    expense_categories: Any
    folders: Any
    grant_funding_sources: Any
    grants: Any
    groups: Any
    interest_charges: Any
    internal_notifications: Any
    lauk_civil_certificated_rates: Any
    lauk_civil_controlled_rates: Any
    lauk_criminal_controlled_rates: Any
    lauk_expense_categories: Any
    line_items: Any
    log_entries: Any
    matter_stages: Any
    matters: Any
    medical_bills: Any
    medical_records: Any
    medical_records_details: Any
    notes: Any
    outstanding_client_balances: Any
    practice_areas: Any
    relationships: Any
    reminders: Any
    report_presets: Any
    report_schedules: Any
    reports: Any
    settings: Any
    task_calendars: Any
    task_template_lists: Any
    task_templates: Any
    task_types: Any
    tasks: Any
    timer: Any
    trust_line_items: Any
    trust_requests: Any
    users: Any
    utbms: Any
    webhooks: Any

class Post:
    activities: Any
    activity_descriptions: Any
    activity_rates: Any
    allocations: Any
    bank_accounts: Any
    bank_transactions: Any
    bank_transfers: Any
    bill_themes: Any
    billable_clients: Any
    billable_matters: Any
    bills: Any
    calendar_entries: Any
    calendar_entry_event_types: Any
    calendars: Any
    clio_payments: Any
    comments: Any
    communications: Any
    contacts: Any
    conversation_messages: Any
    conversations: Any
    court_rules: Any
    credit_memos: Any
    currencies: Any
    custom_actions: Any
    custom_field_sets: Any
    custom_fields: Any
    damages: Any
    document_archives: Any
    document_automations: Any
    document_categories: Any
    document_templates: Any
    documents: Any
    expense_categories: Any
    folders: Any
    grant_funding_sources: Any
    grants: Any
    groups: Any
    interest_charges: Any
    internal_notifications: Any
    lauk_civil_certificated_rates: Any
    lauk_civil_controlled_rates: Any
    lauk_criminal_controlled_rates: Any
    lauk_expense_categories: Any
    line_items: Any
    log_entries: Any
    matter_stages: Any
    matters: Any
    medical_bills: Any
    medical_records: Any
    medical_records_details: Any
    notes: Any
    outstanding_client_balances: Any
    practice_areas: Any
    relationships: Any
    reminders: Any
    report_presets: Any
    report_schedules: Any
    reports: Any
    settings: Any
    task_calendars: Any
    task_template_lists: Any
    task_templates: Any
    task_types: Any
    tasks: Any
    timer: Any
    trust_line_items: Any
    trust_requests: Any
    users: Any
    utbms: Any
    webhooks: Any

class Patch:
    activities: Any
    activity_descriptions: Any
    activity_rates: Any
    allocations: Any
    bank_accounts: Any
    bank_transactions: Any
    bank_transfers: Any
    bill_themes: Any
    billable_clients: Any
    billable_matters: Any
    bills: Any
    calendar_entries: Any
    calendar_entry_event_types: Any
    calendars: Any
    clio_payments: Any
    comments: Any
    communications: Any
    contacts: Any
    conversation_messages: Any
    conversations: Any
    court_rules: Any
    credit_memos: Any
    currencies: Any
    custom_actions: Any
    custom_field_sets: Any
    custom_fields: Any
    damages: Any
    document_archives: Any
    document_automations: Any
    document_categories: Any
    document_templates: Any
    documents: Any
    expense_categories: Any
    folders: Any
    grant_funding_sources: Any
    grants: Any
    groups: Any
    interest_charges: Any
    internal_notifications: Any
    lauk_civil_certificated_rates: Any
    lauk_civil_controlled_rates: Any
    lauk_criminal_controlled_rates: Any
    lauk_expense_categories: Any
    line_items: Any
    log_entries: Any
    matter_stages: Any
    matters: Any
    medical_bills: Any
    medical_records: Any
    medical_records_details: Any
    notes: Any
    outstanding_client_balances: Any
    practice_areas: Any
    relationships: Any
    reminders: Any
    report_presets: Any
    report_schedules: Any
    reports: Any
    settings: Any
    task_calendars: Any
    task_template_lists: Any
    task_templates: Any
    task_types: Any
    tasks: Any
    timer: Any
    trust_line_items: Any
    trust_requests: Any
    users: Any
    utbms: Any
    webhooks: Any

class Delete:
    activities: Any
    activity_descriptions: Any
    activity_rates: Any
    allocations: Any
    bank_accounts: Any
    bank_transactions: Any
    bank_transfers: Any
    bill_themes: Any
    billable_clients: Any
    billable_matters: Any
    bills: Any
    calendar_entries: Any
    calendar_entry_event_types: Any
    calendars: Any
    clio_payments: Any
    comments: Any
    communications: Any
    contacts: Any
    conversation_messages: Any
    conversations: Any
    court_rules: Any
    credit_memos: Any
    currencies: Any
    custom_actions: Any
    custom_field_sets: Any
    custom_fields: Any
    damages: Any
    document_archives: Any
    document_automations: Any
    document_categories: Any
    document_templates: Any
    documents: Any
    expense_categories: Any
    folders: Any
    grant_funding_sources: Any
    grants: Any
    groups: Any
    interest_charges: Any
    internal_notifications: Any
    lauk_civil_certificated_rates: Any
    lauk_civil_controlled_rates: Any
    lauk_criminal_controlled_rates: Any
    lauk_expense_categories: Any
    line_items: Any
    log_entries: Any
    matter_stages: Any
    matters: Any
    medical_bills: Any
    medical_records: Any
    medical_records_details: Any
    notes: Any
    outstanding_client_balances: Any
    practice_areas: Any
    relationships: Any
    reminders: Any
    report_presets: Any
    report_schedules: Any
    reports: Any
    settings: Any
    task_calendars: Any
    task_template_lists: Any
    task_templates: Any
    task_types: Any
    tasks: Any
    timer: Any
    trust_line_items: Any
    trust_requests: Any
    users: Any
    utbms: Any
    webhooks: Any

class Download:
    activities: Any
    activity_descriptions: Any
    activity_rates: Any
    allocations: Any
    bank_accounts: Any
    bank_transactions: Any
    bank_transfers: Any
    bill_themes: Any
    billable_clients: Any
    billable_matters: Any
    bills: Any
    calendar_entries: Any
    calendar_entry_event_types: Any
    calendars: Any
    clio_payments: Any
    comments: Any
    communications: Any
    contacts: Any
    conversation_messages: Any
    conversations: Any
    court_rules: Any
    credit_memos: Any
    currencies: Any
    custom_actions: Any
    custom_field_sets: Any
    custom_fields: Any
    damages: Any
    document_archives: Any
    document_automations: Any
    document_categories: Any
    document_templates: Any
    documents: Any
    expense_categories: Any
    folders: Any
    grant_funding_sources: Any
    grants: Any
    groups: Any
    interest_charges: Any
    internal_notifications: Any
    lauk_civil_certificated_rates: Any
    lauk_civil_controlled_rates: Any
    lauk_criminal_controlled_rates: Any
    lauk_expense_categories: Any
    line_items: Any
    log_entries: Any
    matter_stages: Any
    matters: Any
    medical_bills: Any
    medical_records: Any
    medical_records_details: Any
    notes: Any
    outstanding_client_balances: Any
    practice_areas: Any
    relationships: Any
    reminders: Any
    report_presets: Any
    report_schedules: Any
    reports: Any
    settings: Any
    task_calendars: Any
    task_template_lists: Any
    task_templates: Any
    task_types: Any
    tasks: Any
    timer: Any
    trust_line_items: Any
    trust_requests: Any
    users: Any
    utbms: Any
    webhooks: Any

class Upload:
    activities: Any
    activity_descriptions: Any
    activity_rates: Any
    allocations: Any
    bank_accounts: Any
    bank_transactions: Any
    bank_transfers: Any
    bill_themes: Any
    billable_clients: Any
    billable_matters: Any
    bills: Any
    calendar_entries: Any
    calendar_entry_event_types: Any
    calendars: Any
    clio_payments: Any
    comments: Any
    communications: Any
    contacts: Any
    conversation_messages: Any
    conversations: Any
    court_rules: Any
    credit_memos: Any
    currencies: Any
    custom_actions: Any
    custom_field_sets: Any
    custom_fields: Any
    damages: Any
    document_archives: Any
    document_automations: Any
    document_categories: Any
    document_templates: Any
    documents: Any
    expense_categories: Any
    folders: Any
    grant_funding_sources: Any
    grants: Any
    groups: Any
    interest_charges: Any
    internal_notifications: Any
    lauk_civil_certificated_rates: Any
    lauk_civil_controlled_rates: Any
    lauk_criminal_controlled_rates: Any
    lauk_expense_categories: Any
    line_items: Any
    log_entries: Any
    matter_stages: Any
    matters: Any
    medical_bills: Any
    medical_records: Any
    medical_records_details: Any
    notes: Any
    outstanding_client_balances: Any
    practice_areas: Any
    relationships: Any
    reminders: Any
    report_presets: Any
    report_schedules: Any
    reports: Any
    settings: Any
    task_calendars: Any
    task_template_lists: Any
    task_templates: Any
    task_types: Any
    tasks: Any
    timer: Any
    trust_line_items: Any
    trust_requests: Any
    users: Any
    utbms: Any
    webhooks: Any

class All:
    activities: Any
    activity_descriptions: Any
    activity_rates: Any
    allocations: Any
    bank_accounts: Any
    bank_transactions: Any
    bank_transfers: Any
    bill_themes: Any
    billable_clients: Any
    billable_matters: Any
    bills: Any
    calendar_entries: Any
    calendar_entry_event_types: Any
    calendars: Any
    clio_payments: Any
    comments: Any
    communications: Any
    contacts: Any
    conversation_messages: Any
    conversations: Any
    court_rules: Any
    credit_memos: Any
    currencies: Any
    custom_actions: Any
    custom_field_sets: Any
    custom_fields: Any
    damages: Any
    document_archives: Any
    document_automations: Any
    document_categories: Any
    document_templates: Any
    documents: Any
    expense_categories: Any
    folders: Any
    grant_funding_sources: Any
    grants: Any
    groups: Any
    interest_charges: Any
    internal_notifications: Any
    lauk_civil_certificated_rates: Any
    lauk_civil_controlled_rates: Any
    lauk_criminal_controlled_rates: Any
    lauk_expense_categories: Any
    line_items: Any
    log_entries: Any
    matter_stages: Any
    matters: Any
    medical_bills: Any
    medical_records: Any
    medical_records_details: Any
    notes: Any
    outstanding_client_balances: Any
    practice_areas: Any
    relationships: Any
    reminders: Any
    report_presets: Any
    report_schedules: Any
    reports: Any
    settings: Any
    task_calendars: Any
    task_template_lists: Any
    task_templates: Any
    task_types: Any
    tasks: Any
    timer: Any
    trust_line_items: Any
    trust_requests: Any
    users: Any
    utbms: Any
    webhooks: Any

